export const countries = [
    { id: 4, alpha2: 'af', alpha3: 'afg', ar: 'أفغانستان', en: 'Afghanistan' },
    { id: 8, alpha2: 'al', alpha3: 'alb', ar: 'ألبانيا', en: 'Albania' },
    { id: 12, alpha2: 'dz', alpha3: 'dza', ar: 'الجزائر', en: 'Algeria' },
    { id: 20, alpha2: 'ad', alpha3: 'and', ar: 'أندورا', en: 'Andorra' },
    { id: 24, alpha2: 'ao', alpha3: 'ago', ar: 'أنغولا', en: 'Angola' },
    { id: 28, alpha2: 'ag', alpha3: 'atg', ar: 'أنتيغوا وباربودا', en: 'Antigua and Barbuda' },
    { id: 32, alpha2: 'ar', alpha3: 'arg', ar: 'الأرجنتين', en: 'Argentina' },
    { id: 51, alpha2: 'am', alpha3: 'arm', ar: 'أرمينيا', en: 'Armenia' },
    { id: 36, alpha2: 'au', alpha3: 'aus', ar: 'أستراليا', en: 'Australia' },
    { id: 40, alpha2: 'at', alpha3: 'aut', ar: 'النمسا', en: 'Austria' },
    { id: 31, alpha2: 'az', alpha3: 'aze', ar: 'أذربيجان', en: 'Azerbaijan' },
    { id: 44, alpha2: 'bs', alpha3: 'bhs', ar: 'باهاماس', en: 'Bahamas' },
    { id: 48, alpha2: 'bh', alpha3: 'bhr', ar: 'البحرين', en: 'Bahrain' },
    { id: 50, alpha2: 'bd', alpha3: 'bgd', ar: 'بنغلاديش', en: 'Bangladesh' },
    { id: 52, alpha2: 'bb', alpha3: 'brb', ar: 'باربادوس', en: 'Barbados' },
    { id: 112, alpha2: 'by', alpha3: 'blr', ar: 'بيلاروس', en: 'Belarus' },
    { id: 56, alpha2: 'be', alpha3: 'bel', ar: 'بلجيكا', en: 'Belgium' },
    { id: 84, alpha2: 'bz', alpha3: 'blz', ar: 'بليز', en: 'Belize' },
    { id: 204, alpha2: 'bj', alpha3: 'ben', ar: 'بنين', en: 'Benin' },
    { id: 64, alpha2: 'bt', alpha3: 'btn', ar: 'بوتان', en: 'Bhutan' },
    { id: 68, alpha2: 'bo', alpha3: 'bol', ar: 'بوليفيا', en: 'Bolivia, Plurinational State of' },
    { id: 70, alpha2: 'ba', alpha3: 'bih', ar: 'البوسنة والهرسك', en: 'Bosnia and Herzegovina' },
    { id: 72, alpha2: 'bw', alpha3: 'bwa', ar: 'بوتسوانا', en: 'Botswana' },
    { id: 76, alpha2: 'br', alpha3: 'bra', ar: 'البرازيل', en: 'Brazil' },
    { id: 96, alpha2: 'bn', alpha3: 'brn', ar: 'بروناي', en: 'Brunei Darussalam' },
    { id: 100, alpha2: 'bg', alpha3: 'bgr', ar: 'بلغاريا', en: 'Bulgaria' },
    { id: 854, alpha2: 'bf', alpha3: 'bfa', ar: 'بوركينا فاسو', en: 'Burkina Faso' },
    { id: 108, alpha2: 'bi', alpha3: 'bdi', ar: 'بوروندي', en: 'Burundi' },
    { id: 116, alpha2: 'kh', alpha3: 'khm', ar: 'كمبوديا', en: 'Cambodia' },
    { id: 120, alpha2: 'cm', alpha3: 'cmr', ar: 'الكاميرون', en: 'Cameroon' },
    { id: 124, alpha2: 'ca', alpha3: 'can', ar: 'كندا', en: 'Canada' },
    { id: 132, alpha2: 'cv', alpha3: 'cpv', ar: 'الرأس الأخضر', en: 'Cabo Verde' },
    { id: 140, alpha2: 'cf', alpha3: 'caf', ar: 'جمهورية إفريقيا الوسطى', en: 'Central African Republic' },
    { id: 148, alpha2: 'td', alpha3: 'tcd', ar: 'تشاد', en: 'Chad' },
    { id: 152, alpha2: 'cl', alpha3: 'chl', ar: 'تشيلي', en: 'Chile' },
    { id: 156, alpha2: 'cn', alpha3: 'chn', ar: 'الصين', en: 'China' },
    { id: 170, alpha2: 'co', alpha3: 'col', ar: 'كولومبيا', en: 'Colombia' },
    { id: 174, alpha2: 'km', alpha3: 'com', ar: 'جزر القمر', en: 'Comoros' },
    { id: 178, alpha2: 'cg', alpha3: 'cog', ar: 'جمهورية الكونغو', en: 'Congo' },
    { id: 180, alpha2: 'cd', alpha3: 'cod', ar: 'جمهورية الكونغو الديمقراطية', en: 'Congo, Democratic Republic of the' },
    { id: 188, alpha2: 'cr', alpha3: 'cri', ar: 'كوستاريكا', en: 'Costa Rica' },
    { id: 384, alpha2: 'ci', alpha3: 'civ', ar: 'ساحل العاج', en: "Côte d'Ivoire" },
    { id: 191, alpha2: 'hr', alpha3: 'hrv', ar: 'كرواتيا', en: 'Croatia' },
    { id: 192, alpha2: 'cu', alpha3: 'cub', ar: 'كوبا', en: 'Cuba' },
    { id: 196, alpha2: 'cy', alpha3: 'cyp', ar: 'قبرص', en: 'Cyprus' },
    { id: 203, alpha2: 'cz', alpha3: 'cze', ar: 'جمهورية التشيك', en: 'Czechia' },
    { id: 208, alpha2: 'dk', alpha3: 'dnk', ar: 'الدنمارك', en: 'Denmark' },
    { id: 262, alpha2: 'dj', alpha3: 'dji', ar: 'جيبوتي', en: 'Djibouti' },
    { id: 212, alpha2: 'dm', alpha3: 'dma', ar: 'دومينيكا', en: 'Dominica' },
    { id: 214, alpha2: 'do', alpha3: 'dom', ar: 'جمهورية الدومينيكان', en: 'Dominican Republic' },
    { id: 218, alpha2: 'ec', alpha3: 'ecu', ar: 'الإكوادور', en: 'Ecuador' },
    { id: 818, alpha2: 'eg', alpha3: 'egy', ar: 'مصر', en: 'Egypt' },
    { id: 222, alpha2: 'sv', alpha3: 'slv', ar: 'السلفادور', en: 'El Salvador' },
    { id: 226, alpha2: 'gq', alpha3: 'gnq', ar: 'غينيا الاستوائية', en: 'Equatorial Guinea' },
    { id: 232, alpha2: 'er', alpha3: 'eri', ar: 'إرتريا', en: 'Eritrea' },
    { id: 233, alpha2: 'ee', alpha3: 'est', ar: 'إستونيا', en: 'Estonia' },
    { id: 231, alpha2: 'et', alpha3: 'eth', ar: 'إثيوبيا', en: 'Ethiopia' },
    { id: 242, alpha2: 'fj', alpha3: 'fji', ar: 'فيجي', en: 'Fiji' },
    { id: 246, alpha2: 'fi', alpha3: 'fin', ar: 'فنلندا', en: 'Finland' },
    { id: 250, alpha2: 'fr', alpha3: 'fra', ar: 'فرنسا', en: 'France' },
    { id: 266, alpha2: 'ga', alpha3: 'gab', ar: 'الغابون', en: 'Gabon' },
    { id: 270, alpha2: 'gm', alpha3: 'gmb', ar: 'غامبيا', en: 'Gambia' },
    { id: 268, alpha2: 'ge', alpha3: 'geo', ar: 'جورجيا', en: 'Georgia' },
    { id: 276, alpha2: 'de', alpha3: 'deu', ar: 'ألمانيا', en: 'Germany' },
    { id: 288, alpha2: 'gh', alpha3: 'gha', ar: 'غانا', en: 'Ghana' },
    { id: 300, alpha2: 'gr', alpha3: 'grc', ar: 'اليونان', en: 'Greece' },
    { id: 308, alpha2: 'gd', alpha3: 'grd', ar: 'غرينادا', en: 'Grenada' },
    { id: 320, alpha2: 'gt', alpha3: 'gtm', ar: 'غواتيمالا', en: 'Guatemala' },
    { id: 324, alpha2: 'gn', alpha3: 'gin', ar: 'غينيا', en: 'Guinea' },
    { id: 624, alpha2: 'gw', alpha3: 'gnb', ar: 'غينيا بيساو', en: 'Guinea-Bissau' },
    { id: 328, alpha2: 'gy', alpha3: 'guy', ar: 'غيانا', en: 'Guyana' },
    { id: 332, alpha2: 'ht', alpha3: 'hti', ar: 'هايتي', en: 'Haiti' },
    { id: 340, alpha2: 'hn', alpha3: 'hnd', ar: 'هندوراس', en: 'Honduras' },
    { id: 348, alpha2: 'hu', alpha3: 'hun', ar: 'المجر', en: 'Hungary' },
    { id: 352, alpha2: 'is', alpha3: 'isl', ar: 'آيسلندا', en: 'Iceland' },
    { id: 356, alpha2: 'in', alpha3: 'ind', ar: 'الهند', en: 'India' },
    { id: 360, alpha2: 'id', alpha3: 'idn', ar: 'إندونيسيا', en: 'Indonesia' },
    { id: 364, alpha2: 'ir', alpha3: 'irn', ar: 'إيران', en: 'Iran, Islamic Republic of' },
    { id: 368, alpha2: 'iq', alpha3: 'irq', ar: 'العراق', en: 'Iraq' },
    { id: 372, alpha2: 'ie', alpha3: 'irl', ar: 'أيرلندا', en: 'Ireland' },
    { id: 376, alpha2: 'il', alpha3: 'isr', ar: 'إسرائيل', en: 'Israel' },
    { id: 380, alpha2: 'it', alpha3: 'ita', ar: 'إيطاليا', en: 'Italy' },
    { id: 388, alpha2: 'jm', alpha3: 'jam', ar: 'جامايكا', en: 'Jamaica' },
    { id: 392, alpha2: 'jp', alpha3: 'jpn', ar: 'اليابان', en: 'Japan' },
    { id: 400, alpha2: 'jo', alpha3: 'jor', ar: 'الأردن', en: 'Jordan' },
    { id: 398, alpha2: 'kz', alpha3: 'kaz', ar: 'كازاخستان', en: 'Kazakhstan' },
    { id: 404, alpha2: 'ke', alpha3: 'ken', ar: 'كينيا', en: 'Kenya' },
    { id: 296, alpha2: 'ki', alpha3: 'kir', ar: 'كيريباتي', en: 'Kiribati' },
    { id: 408, alpha2: 'kp', alpha3: 'prk', ar: 'كوريا الشمالية', en: "Korea, Democratic People's Republic of" },
    { id: 410, alpha2: 'kr', alpha3: 'kor', ar: 'كوريا الجنوبية', en: 'Korea, Republic of' },
    { id: 414, alpha2: 'kw', alpha3: 'kwt', ar: 'الكويت', en: 'Kuwait' },
    { id: 417, alpha2: 'kg', alpha3: 'kgz', ar: 'قيرغيزستان', en: 'Kyrgyzstan' },
    { id: 418, alpha2: 'la', alpha3: 'lao', ar: 'لاوس', en: "Lao People's Democratic Republic" },
    { id: 428, alpha2: 'lv', alpha3: 'lva', ar: 'لاتفيا', en: 'Latvia' },
    { id: 422, alpha2: 'lb', alpha3: 'lbn', ar: 'لبنان', en: 'Lebanon' },
    { id: 426, alpha2: 'ls', alpha3: 'lso', ar: 'ليسوتو', en: 'Lesotho' },
    { id: 430, alpha2: 'lr', alpha3: 'lbr', ar: 'ليبيريا', en: 'Liberia' },
    { id: 434, alpha2: 'ly', alpha3: 'lby', ar: 'ليبيا', en: 'Libya' },
    { id: 438, alpha2: 'li', alpha3: 'lie', ar: 'ليختنشتاين', en: 'Liechtenstein' },
    { id: 440, alpha2: 'lt', alpha3: 'ltu', ar: 'ليتوانيا', en: 'Lithuania' }, { id: 442, alpha2: 'lu', alpha3: 'lux', ar: 'لوكسمبورغ', en: 'Luxembourg' },
    { id: 807, alpha2: 'mk', alpha3: 'mkd', ar: 'مقدونيا', en: 'North Macedonia' },
    { id: 450, alpha2: 'mg', alpha3: 'mdg', ar: 'مدغشقر', en: 'Madagascar' },
    { id: 454, alpha2: 'mw', alpha3: 'mwi', ar: 'مالاوي', en: 'Malawi' },
    { id: 458, alpha2: 'my', alpha3: 'mys', ar: 'ماليزيا', en: 'Malaysia' },
    { id: 462, alpha2: 'mv', alpha3: 'mdv', ar: 'جزر المالديف', en: 'Maldives' },
    { id: 466, alpha2: 'ml', alpha3: 'mli', ar: 'مالي', en: 'Mali' },
    { id: 470, alpha2: 'mt', alpha3: 'mlt', ar: 'مالطا', en: 'Malta' },
    { id: 584, alpha2: 'mh', alpha3: 'mhl', ar: 'جزر مارشال', en: 'Marshall Islands' },
    { id: 478, alpha2: 'mr', alpha3: 'mrt', ar: 'موريتانيا', en: 'Mauritania' },
    { id: 480, alpha2: 'mu', alpha3: 'mus', ar: 'موريشيوس', en: 'Mauritius' },
    { id: 484, alpha2: 'mx', alpha3: 'mex', ar: 'المكسيك', en: 'Mexico' },
    { id: 583, alpha2: 'fm', alpha3: 'fsm', ar: 'ولايات ميكرونيسيا المتحدة', en: 'Micronesia, Federated States of' },
    { id: 504, alpha2: 'ma', alpha3: 'mar', ar: 'المغرب', en: 'Morocco' },
    { id: 498, alpha2: 'md', alpha3: 'mda', ar: 'مولدوفا', en: 'Moldova, Republic of' },
    { id: 492, alpha2: 'mc', alpha3: 'mco', ar: 'موناكو', en: 'Monaco' },
    { id: 496, alpha2: 'mn', alpha3: 'mng', ar: 'منغوليا', en: 'Mongolia' },
    { id: 499, alpha2: 'me', alpha3: 'mne', ar: 'الجبل الأسود', en: 'Montenegro' },
    { id: 508, alpha2: 'mz', alpha3: 'moz', ar: 'موزمبيق', en: 'Mozambique' },
    { id: 104, alpha2: 'mm', alpha3: 'mmr', ar: 'ميانمار', en: 'Myanmar' },
    { id: 516, alpha2: 'na', alpha3: 'nam', ar: 'ناميبيا', en: 'Namibia' },
    { id: 520, alpha2: 'nr', alpha3: 'nru', ar: 'ناورو', en: 'Nauru' },
    { id: 524, alpha2: 'np', alpha3: 'npl', ar: 'نيبال', en: 'Nepal' },
    { id: 528, alpha2: 'nl', alpha3: 'nld', ar: 'هولندا', en: 'Netherlands' },
    { id: 554, alpha2: 'nz', alpha3: 'nzl', ar: 'نيوزيلندا', en: 'New Zealand' },
    { id: 558, alpha2: 'ni', alpha3: 'nic', ar: 'نيكاراغوا', en: 'Nicaragua' },
    { id: 562, alpha2: 'ne', alpha3: 'ner', ar: 'النيجر', en: 'Niger' },
    { id: 566, alpha2: 'ng', alpha3: 'nga', ar: 'نيجيريا', en: 'Nigeria' },
    { id: 578, alpha2: 'no', alpha3: 'nor', ar: 'النرويج', en: 'Norway' },
    { id: 512, alpha2: 'om', alpha3: 'omn', ar: 'عُمان', en: 'Oman' },
    { id: 586, alpha2: 'pk', alpha3: 'pak', ar: 'باكستان', en: 'Pakistan' },
    { id: 585, alpha2: 'pw', alpha3: 'plw', ar: 'بالاو', en: 'Palau' },
    { id: 591, alpha2: 'pa', alpha3: 'pan', ar: 'بنما', en: 'Panama' },
    { id: 598, alpha2: 'pg', alpha3: 'png', ar: 'بابوا غينيا الجديدة', en: 'Papua New Guinea' },
    { id: 600, alpha2: 'py', alpha3: 'pry', ar: 'باراغواي', en: 'Paraguay' },
    { id: 604, alpha2: 'pe', alpha3: 'per', ar: 'بيرو', en: 'Peru' },
    { id: 608, alpha2: 'ph', alpha3: 'phl', ar: 'الفلبين', en: 'Philippines' },
    { id: 616, alpha2: 'pl', alpha3: 'pol', ar: 'بولندا', en: 'Poland' },
    { id: 620, alpha2: 'pt', alpha3: 'prt', ar: 'البرتغال', en: 'Portugal' },
    { id: 634, alpha2: 'qa', alpha3: 'qat', ar: 'قطر', en: 'Qatar' },
    { id: 642, alpha2: 'ro', alpha3: 'rou', ar: 'رومانيا', en: 'Romania' },
    { id: 643, alpha2: 'ru', alpha3: 'rus', ar: 'روسيا', en: 'Russian Federation' },
    { id: 646, alpha2: 'rw', alpha3: 'rwa', ar: 'رواندا', en: 'Rwanda' },
    { id: 659, alpha2: 'kn', alpha3: 'kna', ar: 'سانت كيتس ونيفيس', en: 'Saint Kitts and Nevis' },
    { id: 662, alpha2: 'lc', alpha3: 'lca', ar: 'سانت لوسيا', en: 'Saint Lucia' },
    { id: 670, alpha2: 'vc', alpha3: 'vct', ar: 'سانت فينسنت والغرينادين', en: 'Saint Vincent and the Grenadines' },
    { id: 882, alpha2: 'ws', alpha3: 'wsm', ar: 'ساموا', en: 'Samoa' },
    { id: 674, alpha2: 'sm', alpha3: 'smr', ar: 'سان مارينو', en: 'San Marino' },
    { id: 678, alpha2: 'st', alpha3: 'stp', ar: 'ساو تومي وبرينسيب', en: 'Sao Tome and Principe' },
    { id: 682, alpha2: 'sa', alpha3: 'sau', ar: 'السعودية', en: 'Saudi Arabia' },
    { id: 686, alpha2: 'sn', alpha3: 'sen', ar: 'السنغال', en: 'Senegal' },
    { id: 688, alpha2: 'rs', alpha3: 'srb', ar: 'صربيا', en: 'Serbia' },
    { id: 690, alpha2: 'sc', alpha3: 'syc', ar: 'سيشل', en: 'Seychelles' },
    { id: 694, alpha2: 'sl', alpha3: 'sle', ar: 'سيراليون', en: 'Sierra Leone' },
    { id: 702, alpha2: 'sg', alpha3: 'sgp', ar: 'سنغافورة', en: 'Singapore' },
    { id: 703, alpha2: 'sk', alpha3: 'svk', ar: 'سلوفاكيا', en: 'Slovakia' },
    { id: 705, alpha2: 'si', alpha3: 'svn', ar: 'سلوفينيا', en: 'Slovenia' },
    { id: 90, alpha2: 'sb', alpha3: 'slb', ar: 'جزر سليمان', en: 'Solomon Islands' },
    { id: 706, alpha2: 'so', alpha3: 'som', ar: 'الصومال', en: 'Somalia' },
    { id: 710, alpha2: 'za', alpha3: 'zaf', ar: 'جنوب إفريقيا', en: 'South Africa' },
    { id: 728, alpha2: 'ss', alpha3: 'ssd', ar: 'جنوب السودان', en: 'South Sudan' },
    { id: 724, alpha2: 'es', alpha3: 'esp', ar: 'إسبانيا', en: 'Spain' },
    { id: 144, alpha2: 'lk', alpha3: 'lka', ar: 'سريلانكا', en: 'Sri Lanka' },
    { id: 729, alpha2: 'sd', alpha3: 'sdn', ar: 'السودان', en: 'Sudan' },
    { id: 740, alpha2: 'sr', alpha3: 'sur', ar: 'سورينام', en: 'Suriname' },
    { id: 748, alpha2: 'sz', alpha3: 'swz', ar: 'إسواتيني', en: 'Eswatini' },
    { id: 752, alpha2: 'se', alpha3: 'swe', ar: 'السويد', en: 'Sweden' },
    { id: 756, alpha2: 'ch', alpha3: 'che', ar: 'سويسرا', en: 'Switzerland' },
    { id: 760, alpha2: 'sy', alpha3: 'syr', ar: 'سوريا', en: 'Syrian Arab Republic' },
    { id: 762, alpha2: 'tj', alpha3: 'tjk', ar: 'طاجيكستان', en: 'Tajikistan' },
    { id: 834, alpha2: 'tz', alpha3: 'tza', ar: 'تنزانيا', en: 'Tanzania, United Republic of' },
    { id: 764, alpha2: 'th', alpha3: 'tha', ar: 'تايلاند', en: 'Thailand' },
    { id: 626, alpha2: 'tl', alpha3: 'tls', ar: 'تيمور الشرقية', en: 'Timor-Leste' },
    { id: 768, alpha2: 'tg', alpha3: 'tgo', ar: 'توغو', en: 'Togo' },
    { id: 776, alpha2: 'to', alpha3: 'ton', ar: 'تونغا', en: 'Tonga' },
    { id: 780, alpha2: 'tt', alpha3: 'tto', ar: 'ترينيداد وتوباغو', en: 'Trinidad and Tobago' },
    { id: 788, alpha2: 'tn', alpha3: 'tun', ar: 'تونس', en: 'Tunisia' },
    { id: 792, alpha2: 'tr', alpha3: 'tur', ar: 'تركيا', en: 'Türkiye' },
    { id: 795, alpha2: 'tm', alpha3: 'tkm', ar: 'تركمانستان', en: 'Turkmenistan' },
    { id: 798, alpha2: 'tv', alpha3: 'tuv', ar: 'توفالو', en: 'Tuvalu' },
    { id: 800, alpha2: 'ug', alpha3: 'uga', ar: 'أوغندا', en: 'Uganda' },
    { id: 804, alpha2: 'ua', alpha3: 'ukr', ar: 'أوكرانيا', en: 'Ukraine' },
    { id: 784, alpha2: 'ae', alpha3: 'are', ar: 'الإمارات العربية المتحدة', en: 'United Arab Emirates' },
    { id: 826, alpha2: 'gb', alpha3: 'gbr', ar: 'المملكة المتحدة', en: 'United Kingdom of Great Britain and Northern Ireland' },
    { id: 840, alpha2: 'us', alpha3: 'usa', ar: 'الولايات المتحدة', en: 'United States of America' },
    { id: 858, alpha2: 'uy', alpha3: 'ury', ar: 'الأوروغواي', en: 'Uruguay' },
    { id: 860, alpha2: 'uz', alpha3: 'uzb', ar: 'أوزبكستان', en: 'Uzbekistan' },
    { id: 548, alpha2: 'vu', alpha3: 'vut', ar: 'فانواتو', en: 'Vanuatu' },
    { id: 862, alpha2: 've', alpha3: 'ven', ar: 'فنزويلا', en: 'Venezuela, Bolivarian Republic of' },
    { id: 704, alpha2: 'vn', alpha3: 'vnm', ar: 'فيتنام', en: 'Viet Nam' },
    { id: 887, alpha2: 'ye', alpha3: 'yem', ar: 'اليمن', en: 'Yemen' },
    { id: 894, alpha2: 'zm', alpha3: 'zmb', ar: 'زامبيا', en: 'Zambia' },
    { id: 716, alpha2: 'zw', alpha3: 'zwe', ar: 'زيمبابوي', en: 'Zimbabwe'
    }
]